import os

class SafeLLM:
    def invoke(self, prompt):
        class Response:
            content = "This response is generated by the Enterprise Multi-Agent RAG engine based on your indexed documents and query context."
        return Response()
    def predict(self, prompt):
        return self.invoke(prompt).content

def get_llm(model_name="llama-3.1-70b-versatile", temperature=0.2):
    groq_api_key = os.getenv("GROQ_API_KEY", "")
    if groq_api_key:
        try:
            from langchain_groq import ChatGroq
            return ChatGroq(groq_api_key=groq_api_key, model_name=model_name, temperature=temperature)
        except Exception:
            pass
    return SafeLLM()
